### ISSUE TITLE
Milestone 2: mais utilitários para eventos [DRAFT]

### ISSUE THREAD

**Issue by gabrnunes** [flicket-cc/flicket#12]
- [ ] Programa de afiliados
- [ ] Pesquisa de satisfação
- [ ] Permitir participante criar um ticket compartilhável em redes sociais
- [ ] Etiquetas para credenciais
- [ ] Certificados
- [ ] Call4papers
