### ISSUE TITLE
Milestone 3: rede social [DRAFT]

### ISSUE THREAD

**Issue by gabrnunes** [flicket-cc/flicket#13]
- [ ] Pensei em se basear um pouco em como o GitHub funciona
- [ ] criar perfil
- [ ] timeline de eventos ou tags que segue
- [ ] newsletter semanal com eventos sugeridos (por região ou por tema)
- [ ] possível mencionar palestrantes com o perfil que eles tiverem no Flicket
